name: CommandCooldown
main: me.Darrionat.CommandCooldown.Main
description: An easy way to add cooldowns to commands
version: 1.31

commands:
  commandcooldown:
    aliases: [cc, commandcd, cmdcd]
    usage: </command> <help/list/add/remove/reload/bypass>
    
permissions:
  commandcooldown.*:
    description: Gives access to all CC commands
    children:
      commandcooldown.admin: true
  commandcooldown.admin:
    description: Allows a player to use all commands
    default: op